name: flutter_go_demo
description: Demo showing Flutter calling Go via FFI
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1

flutter:
  uses-material-design: true
